name: Swift

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
        swift: ["5.1"]
    runs-on: ${{ matrix.os }}
    env:
      SWIFT_VERSION: ${{ matrix.swift }}
      SWIFT_EXEC: .swiftenv/shims/swift
    steps:
    - uses: actions/checkout@v2
    - name: Install Swift
      run: |
        git clone https://github.com/kylef/swiftenv.git ~/.swiftenv
        ~/.swiftenv/bin/swiftenv install $SWIFT_VERSION --skip-existing
        ~/.swiftenv/bin/swiftenv rehash
    - name: Build
      run: |
        ~/$SWIFT_EXEC --version
        ~/$SWIFT_EXEC build -v
    - name: Test
      run: |
        ~/$SWIFT_EXEC test -v --enable-code-coverage
    - name: Upload Code Coverage
      run: |
        if [ "$(uname)" == "Linux" ]; then
            echo Skipping Code Coverage upload for Linux
        else
            xcrun llvm-cov export -format="lcov" .build/debug/CBORCodingPackageTests.xctest/Contents/MacOS/CBORCodingPackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov
            bash <(curl https://codecov.io/bash)
        fi
